name:                iox-hello-haskell
version:             0.1.0.0
github:              "githubuser/iox-hello-haskell"
license:             OtherLicense
author:              "Naoto Shimazaki"
maintainer:          "nshimaza@cisco.com"
copyright:           "2019 Naoto Shimazaki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nshimaza/iox-hello-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  iox-hello-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iox-hello-haskell
    - bytestring
    - http-types
    - unix-time
    - wai
    - warp
